### ISSUE TITLE
How to customize templates an change IP from 127.0.0.1 other IP address where DMS is installed

### ISSUE THREAD

**Issue by akashdubey251996** [FlexSolution/AlfrescoResetPassword#14]
As my DMS is installed at server instead of localhost, but on resetting the password the link which i am receiving in the mail is giving alfresco  at some place. I want to change that Alfresco name .

And while clicking on the link it is giving
http://127.0.0.1:8080/share/page/changePassWF?token=LQ9feuhVNF69t3sdiKAeJh4mgYAk4Eme66f9c98-82a9-
and error on the page ..

What things i need to change so that it works perfectly.

**Comment by sp4rry** [comment]
Hi I have the same question as @akashdubey251996 I changed the share.host in global properties that removed the 127.0.0.1 however it still left it with http://newhostname:8080/share.  Our alfresco is hidden behind a reverse proxy and I need to display an accessible https://newhostname/share url so they can access it.  

I don't want to go the route of having to hardcode values into the email template

Thanks
Steve

**Comment by sp4rry** [comment]
Just a quick update, I found that if you edit the share properties in alfresco-global.properties it works

share.context=share
share.host=mydomain.com
share.port=443
share.protocol=https

with this I get the link in the email and the images resolving to 
https://mydomain.com//share
