### ISSUE TITLE
Change Sender email from users to a static one using mail.from not working

### ISSUE THREAD

**Issue by sp4rry** [FlexSolution/AlfrescoResetPassword#15]
Hi, I love the plug in however I'm having an issue with changing the from email address.  it always sends from the the actual users email.  

AWS SES doesn't like sending from unknown domains.  I have tried changing the setting in the global properties file for the mail.from properties without any success 

mail.from.enabled=true (tried both true and false)
mail.from.default=alfresco@mydomain.com

If you could point out where this is being derived from in the code I can go ahead and make my changes.

Thanks
S

**Comment by danzone** [comment]
I have the same issue, and a collateral is that often email sent from Alfresco are marked as spam, and end users complain that they didn't receive any reset email. I'm aware that one can set the property
`mail.from.enabled=false`
in Alfresco Global Properties, and I'm going to try it, but it would be better fix this issue. Could you please provide some hint? This plugin is really useful.

**Comment by sp4rry** [comment]
setting that to false and setting mail.from.default to a valid domain works for me.  We are sending via AWS SES so need to send from a recognised domain.  when it is set to true it just uses the users email which obviously isn't a domain we own and can validate on AWS SES.  We've not experienced the issue with emails being marked as spam.  obviously the share_host and ports etc also need to be set so that the links in the email actually work.

Thanks
S

**Comment by danzone** [comment]
Thank you @sp4rry for your feedback, very valuable. Actually I installed this module some month ago and it worked well. Just today a colleague of mine reported me this issue and so I started to investigate.
Thank you very much!
