### ISSUE TITLE
error 00260020 

### ISSUE THREAD

**Issue by cvalf** [FlexSolution/AlfrescoResetPassword#2]
after typing the user and pressing reset
00260020 Wrapped Exception (with status template): clientName is a mandatory parameter.

![alfresco1](https://user-images.githubusercontent.com/27368980/35464425-9cc3b24a-02d4-11e8-99b1-1b71f5a6e120.PNG)
![alfresco2](https://user-images.githubusercontent.com/27368980/35464444-b728d69c-02d4-11e8-9f9a-a3c2f1ba7cc9.PNG)

![alfresco](https://user-images.githubusercontent.com/27368980/35464395-7470be14-02d4-11e8-9200-8092cf7b5235.PNG)

**Comment by FlexSolution** [comment]
Fixed
