### ISSUE TITLE
Activity task variable empty on reset password link Alfresco Share

### ISSUE THREAD

**Issue by jdomingt** [FlexSolution/AlfrescoResetPassword#3]
Hi, I have this scenario:

 

alfresco-aos-module 'version 1.1.6.

alfresco-share-services' version 5.2.0

alfresco-login-reset-repo 'version 1.1

org.alfresco.integrations.google.docs' version 3.0.4.

org_alfresco_module_wcmquickstart 'version 5.2.f.

alfresco-share-services' version 5.2.0.

 

When the users uses the forgot password workflow provided by alfresco-login-reset-repo 'version 1.1 (https://github.com/teqnology/alfresco-login-reset) , we experience a very strange situation.

When the users receive the email with the link to reset the password, get an error message "Activity data not found".

We check on alfresco tasks, that the workflow is initiated and have an activity ID but the error message it's true because the activity variable it's empty, the result is that the users can't reset their passwords.

 

After some tests, we found that if the admin user logon on alfresco share and then use the reset password workflow, the link to reset the password now appears with the activity variable with content and reviewing the task created on alfresco says that the admin user is the creator of the task and then the reset password works fine.

 

Then, the activity variable of the reset password ink get's the latest user logged on alfresco NOT the user that starts the reset password workflow... somebody could help us ?

 

Thank you,

 

Regards,

 

Joan

**Comment by FlexSolution** [comment]
Sorry, it is the wrong place for the issue. You described the problem in the module which was developed by another company. Please contact them to get help
