### ISSUE TITLE
Workflow Owner

### ISSUE THREAD

**Issue by gb-123-git** [FlexSolution/AlfrescoResetPassword#8]
Hi,

I noticed that the workflow owner becomes some "workspace node". This makes it impossible to delete the workflow. 
Also, plaintext password is visible in the workflow.

Suggestion : Make the owner of the workflow as GROUP_ADMINISTRATORS so that the admins can delete the workflows to clean the database. Also hide the password field so that the admins are not able to see the actual password.

Regards,

PS: I used the latest 1.2.0 Snapshot version to test.
Alfresco Version : 6.2

**Comment by FlexSolution** [comment]
Thanks for the reporting of the issue. We will solve it as soon as we get some free time

**Comment by FlexSolution** [comment]
Fixed in release 1.2.0
